name: stohp_driver_app
description: An application for Stohp drivers.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  meta: ^1.1.8
  flutter_secure_storage: ^3.3.1+1
  flutter_ringtone_player: ^2.0.0

  # UI
  rflutter_alert: ^1.0.3

  # Util
  http: ^0.12.0+4
  qr_flutter: ^3.2.0
  vibration: ^1.2.2
  web_socket_channel: ^1.1.0
  path_provider: ^1.6.1

  # Bloc
  flutter_bloc: ^3.1.0
  rxdart: ^0.23.1
  equatable: ^1.0.2

  # Location
  geolocator: ^5.1.5
  google_maps_flutter: 0.5.21+15
  google_maps_webservice: ^0.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: true
  ios: true
  image_path_ios: "assets/icons/logo-badge.png"
  image_path_android: "assets/icons/logo-badge.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/logo-badge-foreground.png"

flutter:
  uses-material-design: true
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
    - family:  StohpDriver
      fonts:
       - asset: assets/fonts/StohpDriver.ttf
  assets:
    - assets/icons/
    - assets/images/
