/// Flutter icons StohpDriver
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  StohpDriver
///      fonts:
///       - asset: fonts/StohpDriver.ttf
///
/// 
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
///
import 'package:flutter/widgets.dart';

class StohpDriver {
  StohpDriver._();

  static const _kFontFam = 'StohpDriver';

  static const IconData scan = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData arrows_cw = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData qr = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData block = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData user = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData car = const IconData(0xe84e, fontFamily: _kFontFam);
}
